// Code generated by go generate; DO NOT EDIT.
// To regenerate: task gen-imports

package ous

// ServiceResourcePath is the canonical path for this resource type.
const ServiceResourcePath = "organizations/ous"
