// Code generated by go generate; DO NOT EDIT.
// To regenerate: task gen-imports

package hostedzones

// ServiceResourcePath is the canonical path for this resource type.
const ServiceResourcePath = "route53/hosted-zones"
