version: "2"
run:
  tests: true
linters:
  default: none
  enable:
    - bodyclose
    - errcheck
    - errorlint
    - goconst
    - gosec
    - govet
    - ineffassign
    - misspell
    - noctx
    - staticcheck
    - unconvert
    - unused
  settings:
    goconst:
      min-len: 5
      min-occurrences: 5
    gosec:
      excludes:
        - G104
        - G204
        - G304
        - G115
        - G301
        - G101
        - G306
  exclusions:
    generated: lax
    rules:
      - linters:
          - errcheck
          - errorlint
          - goconst
        path: _test\.go
      - linters:
          - goconst
        source: case ".*":|return ".*"|== ".*"
      - linters:
          - staticcheck
        path: custom/.*/.*\.go
        text: SA1019.*deprecated
    paths:
      - .*\.pb\.go
      - .*\.gen\.go
      - vendor
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/clawscli/claws
  exclusions:
    generated: lax
    paths:
      - .*\.pb\.go
      - .*\.gen\.go
      - vendor
      - third_party$
      - builtin$
      - examples$
