run:
  timeout: 5m
  tests: true

issues:
  exclude-dirs:
    - vendor
  exclude-files:
    - ".*\\.pb\\.go"
    - ".*\\.gen\\.go"
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - goconst
        - errorlint
        - errcheck
    - linters:
        - goconst
      source: "case \".*\":|return \".*\"|== \".*\""
    - linters:
        - staticcheck
      text: "SA1019.*deprecated"
      path: "custom/.*/.*\\.go"

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell
    - errorlint
    - unconvert
    - goconst
    # Security linters
    - gosec
    - bodyclose
    - noctx

linters-settings:
  goimports:
    local-prefixes: github.com/clawscli/claws
  gofmt:
    simplify: true
  goconst:
    min-len: 5
    min-occurrences: 5
  gosec:
    excludes:
      - G104  # Audit errors not checked (covered by errcheck)
      - G204  # Subprocess with variable - intentional for CLI actions
      - G304  # File path from variable - intentional for log/config
      - G115  # int->int32 conversion - pageSize always < 1000
      - G301  # Directory permissions - test only
      - G101  # Hardcoded credentials - test examples only
