version: 2

builds:
  # ARM64 build (always)
  - id: arm64
    main: ./cmd/claws
    binary: claws
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

  # AMD64 build (skip for prereleases unless tag contains "amd64" or "all")
  # Examples: v0.1.0-rc1 (skip), v0.1.0-rc1-amd64 (build), v0.1.0-rc1-all (build), v0.1.0 (build)
  - id: amd64
    main: ./cmd/claws
    binary: claws
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    ldflags:
      - -s -w -X main.version={{.Version}}
    skip: '{{ and (ne .Prerelease "") (not (or (contains .Tag "amd64") (contains .Tag "all"))) }}'

  # Windows build (skip for prereleases unless tag contains "win" or "all")
  # Examples: v0.1.0-rc1 (skip), v0.1.0-rc1-win (build), v0.1.0-rc1-all (build), v0.1.0 (build)
  - id: windows
    main: ./cmd/claws
    binary: claws
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w -X main.version={{.Version}}
    skip: '{{ and (ne .Prerelease "") (not (or (contains .Tag "win") (contains .Tag "all"))) }}'

archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  prerelease: auto

homebrew_casks:
  - skip_upload: auto
    repository:
      owner: clawscli
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: https://github.com/clawscli/claws
    description: "Terminal UI for AWS resource management"
    license: "Apache-2.0"
    binaries:
      - claws
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/claws"]
          end
