version: 2

builds:
  - main: ./cmd/claws
    binary: claws
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - repository:
      owner: clawscli
      name: homebrew-tap
    homepage: https://github.com/clawscli/claws
    description: "Terminal UI for AWS resource management"
    license: "Apache-2.0"
    install: |
      bin.install "claws"
    test: |
      system "#{bin}/claws", "--help"
