version: '3'

vars:
  LOCALSTACK_CONTAINER: claws-localstack

# Shared environment for LocalStack tasks
env: &localstack-env
  AWS_ENDPOINT_URL: http://localhost:4566
  AWS_ACCESS_KEY_ID: test
  AWS_SECRET_ACCESS_KEY: test
  AWS_DEFAULT_REGION: us-east-1
  AWS_EC2_METADATA_DISABLED: "true"

tasks:
  build:
    desc: Build the claws binary
    cmds:
      - go build -o claws ./cmd/claws

  run:
    desc: Run claws
    deps: [build]
    cmds:
      - ./claws

  test:
    desc: Run all tests
    cmds:
      - go test ./...

  test-race:
    desc: Run tests with race detector (requires CGO and C compiler)
    cmds:
      - CGO_ENABLED=1 go test -race ./...

  test-cover:
    desc: Run tests with coverage report
    cmds:
      - go test ./... -cover -coverprofile=coverage.out
      - go tool cover -func=coverage.out | tail -1

  # LocalStack tasks
  localstack:start:
    desc: Start LocalStack container
    cmds:
      - docker start {{.LOCALSTACK_CONTAINER}} 2>/dev/null || docker run -d --name {{.LOCALSTACK_CONTAINER}} -p 4566:4566 localstack/localstack:4.12.0
      - |
        echo "Waiting for LocalStack to be ready..."
        for i in $(seq 1 30); do
          if curl -s --connect-timeout 2 --max-time 5 http://localhost:4566/_localstack/health 2>/dev/null | grep -qE '"s3": "(available|running)"'; then
            echo "LocalStack started at http://localhost:4566"
            exit 0
          fi
          sleep 1
        done
        echo "LocalStack failed to start within 30s"
        exit 1

  localstack:stop:
    desc: Stop LocalStack container
    cmds:
      - docker stop {{.LOCALSTACK_CONTAINER}} || true

  localstack:clean:
    desc: Remove LocalStack container
    cmds:
      - docker rm -f {{.LOCALSTACK_CONTAINER}} || true

  localstack:logs:
    desc: Show LocalStack logs
    cmds:
      - docker logs -f {{.LOCALSTACK_CONTAINER}}

  localstack:demo-setup:
    desc: Create demo resources in LocalStack (VPCs, EC2, S3)
    deps: [localstack:start]
    env: *localstack-env
    cmds:
      - ./scripts/localstack-demo-setup.sh

  localstack:demo-cleanup:
    desc: Cleanup demo resources from LocalStack
    env: *localstack-env
    cmds:
      - ./scripts/localstack-demo-cleanup.sh

  localstack:demo:
    desc: Run claws against LocalStack
    deps: [build, localstack:start]
    env: *localstack-env
    cmds:
      - ./claws

  demo:record:
    desc: Record all demos (gif + screenshots) using VHS + LocalStack
    deps: [build, localstack:start, localstack:demo-setup]
    preconditions:
      - sh: '[ "$(uname -s)" = "Linux" ]'
        msg: "demo:record requires Linux (--network host not supported on macOS/Windows)"
    cmds:
      - task: demo:record:gif
      - task: demo:record:themes
      - task: demo:record:features

  demo:record:gif:
    desc: Record demo.gif only
    deps: [build, localstack:start, localstack:demo-setup]
    preconditions:
      - sh: '[ "$(uname -s)" = "Linux" ]'
        msg: "demo:record requires Linux (--network host not supported on macOS/Windows)"
    cmds:
      - |
        docker run --rm --network host \
          -v "$(pwd)":/vhs \
          -v "$(pwd)/scripts/demo-aws-config:/root/.aws:ro" \
          -e AWS_ENDPOINT_URL=http://localhost:4566 \
          -e AWS_EC2_METADATA_DISABLED=true \
          ghcr.io/charmbracelet/vhs docs/tapes/demo.tape

  demo:record:themes:
    desc: Record theme screenshots only
    deps: [build, localstack:start, localstack:demo-setup]
    preconditions:
      - sh: '[ "$(uname -s)" = "Linux" ]'
        msg: "demo:record requires Linux (--network host not supported on macOS/Windows)"
    cmds:
      - |
        docker run --rm --network host \
          -v "$(pwd)":/vhs \
          -v "$(pwd)/scripts/demo-aws-config:/root/.aws:ro" \
          -e AWS_ENDPOINT_URL=http://localhost:4566 \
          -e AWS_EC2_METADATA_DISABLED=true \
          ghcr.io/charmbracelet/vhs docs/tapes/themes.tape

  demo:record:features:
    desc: Record feature screenshots only
    deps: [build, localstack:start, localstack:demo-setup]
    preconditions:
      - sh: '[ "$(uname -s)" = "Linux" ]'
        msg: "demo:record requires Linux (--network host not supported on macOS/Windows)"
    cmds:
      - |
        docker run --rm --network host \
          -v "$(pwd)":/vhs \
          -v "$(pwd)/scripts/demo-aws-config:/root/.aws:ro" \
          -e AWS_ENDPOINT_URL=http://localhost:4566 \
          -e AWS_EC2_METADATA_DISABLED=true \
          ghcr.io/charmbracelet/vhs docs/tapes/features.tape

  test-localstack:
    desc: Run integration tests with LocalStack
    deps: [localstack:start]
    env: *localstack-env
    cmds:
      - go test -v ./... -tags=integration -timeout 60s

  test-pty:
    desc: Run PTY test (TUI test in headless environment)
    cmds:
      - go test -v ./internal/app/ -run TestPTY -timeout 60s

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -f claws
      - rm -f coverage.out

  lint:
    desc: Run linters (requires golangci-lint)
    cmds:
      - golangci-lint run

  fmt:
    desc: Format code
    cmds:
      - go fmt ./...

  gen-imports:
    desc: Regenerate cmd/claws/imports_custom.go from custom/**/register.go
    cmds:
      - go run ./scripts/gen-imports

  release:
    desc: "Create a new release (usage: task release -- v0.1.0)"
    cmds:
      - |
        VERSION="{{.CLI_ARGS}}"
        if [ -z "$VERSION" ]; then
          echo "Usage: task release -- v0.x.x"
          exit 1
        fi
        if ! echo "$VERSION" | grep -qE '^v[0-9]+\.[0-9]+\.[0-9]+$'; then
          echo "Error: Version must be in format v0.x.x (e.g., v0.1.0)"
          exit 1
        fi
        echo "Creating release $VERSION..."
        git tag -a "$VERSION" -m "Release $VERSION"
        git push origin "$VERSION"
        echo "Release $VERSION created and pushed!"
        echo "GitHub Actions will build and publish the release."
