// Code generated by go generate; DO NOT EDIT.
// To regenerate: task gen-imports

package detectors

// ServiceResourcePath is the canonical path for this resource type.
const ServiceResourcePath = "guardduty/detectors"
