// Code generated by go generate; DO NOT EDIT.
// To regenerate: task gen-imports

package indexes

// ServiceResourcePath is the canonical path for this resource type.
const ServiceResourcePath = "s3vectors/indexes"
