// Code generated by go generate; DO NOT EDIT.
// To regenerate: task gen-imports

package prompts

// ServiceResourcePath is the canonical path for this resource type.
const ServiceResourcePath = "bedrock-agent/prompts"
