// Code generated by go generate; DO NOT EDIT.
// To regenerate: task gen-imports

package recoverypoints

// ServiceResourcePath is the canonical path for this resource type.
const ServiceResourcePath = "backup/recovery-points"
