// Code generated by go generate; DO NOT EDIT.
// To regenerate: task gen-imports

package launchtemplates

// ServiceResourcePath is the canonical path for this resource type.
const ServiceResourcePath = "ec2/launch-templates"
