// Code generated by go generate; DO NOT EDIT.
// To regenerate: task gen-imports

package classificationjobs

// ServiceResourcePath is the canonical path for this resource type.
const ServiceResourcePath = "macie2/classification-jobs"
