// Code generated by go generate; DO NOT EDIT.
// To regenerate: task gen-imports

package datasources

// ServiceResourcePath is the canonical path for this resource type.
const ServiceResourcePath = "appsync/data-sources"
