// Code generated by go generate; DO NOT EDIT.
// To regenerate: task gen-imports

package resources

// ServiceResourcePath is the canonical path for this resource type.
const ServiceResourcePath = "cloudformation/resources"
