// Code generated by go generate; DO NOT EDIT.
// To regenerate: task gen-imports

package elasticips

// ServiceResourcePath is the canonical path for this resource type.
const ServiceResourcePath = "ec2/elastic-ips"
