// Code generated by go generate; DO NOT EDIT.
// To regenerate: task gen-imports

package runtimes

// ServiceResourcePath is the canonical path for this resource type.
const ServiceResourcePath = "bedrock-agentcore/runtimes"
