// Code generated by go generate; DO NOT EDIT.
// To regenerate: task gen-imports

package internetgateways

// ServiceResourcePath is the canonical path for this resource type.
const ServiceResourcePath = "vpc/internet-gateways"
