// Code generated by go generate; DO NOT EDIT.
// To regenerate: task gen-imports

package targets

// ServiceResourcePath is the canonical path for this resource type.
const ServiceResourcePath = "elbv2/targets"
