// Code generated by go generate; DO NOT EDIT.
// To regenerate: task gen-imports

package jobruns

// ServiceResourcePath is the canonical path for this resource type.
const ServiceResourcePath = "glue/job-runs"
