// Code generated by go generate; DO NOT EDIT.
// To regenerate: task gen-imports

package buckets

// ServiceResourcePath is the canonical path for this resource type.
const ServiceResourcePath = "s3vectors/buckets"
