// Code generated by go generate; DO NOT EDIT.
// To regenerate: task gen-imports

package images

// ServiceResourcePath is the canonical path for this resource type.
const ServiceResourcePath = "ecr/images"
