// Code generated by go generate; DO NOT EDIT.
// To regenerate: task gen-imports

package fleets

// ServiceResourcePath is the canonical path for this resource type.
const ServiceResourcePath = "gamelift/fleets"
