// Code generated by go generate; DO NOT EDIT.
// To regenerate: task gen-imports
//
// This file contains blank imports that register custom resource implementations.
// Each import triggers the init() function in that package, which registers
// the DAO and Renderer with the global registry.

package main

import (
	// IAM Access Analyzer
	_ "github.com/clawscli/claws/custom/accessanalyzer/analyzers"
	_ "github.com/clawscli/claws/custom/accessanalyzer/findings"

	// ACM
	_ "github.com/clawscli/claws/custom/acm/certificates"

	// API Gateway
	_ "github.com/clawscli/claws/custom/apigateway/http-apis"
	_ "github.com/clawscli/claws/custom/apigateway/rest-apis"
	_ "github.com/clawscli/claws/custom/apigateway/stages"
	_ "github.com/clawscli/claws/custom/apigateway/stages-v2"

	// App Runner
	_ "github.com/clawscli/claws/custom/apprunner/operations"
	_ "github.com/clawscli/claws/custom/apprunner/services"

	// AppSync
	_ "github.com/clawscli/claws/custom/appsync/data-sources"
	_ "github.com/clawscli/claws/custom/appsync/graphql-apis"

	// Athena
	_ "github.com/clawscli/claws/custom/athena/query-executions"
	_ "github.com/clawscli/claws/custom/athena/workgroups"

	// Auto Scaling
	_ "github.com/clawscli/claws/custom/autoscaling/activities"
	_ "github.com/clawscli/claws/custom/autoscaling/groups"

	// AWS Backup
	_ "github.com/clawscli/claws/custom/backup/backup-jobs"
	_ "github.com/clawscli/claws/custom/backup/copy-jobs"
	_ "github.com/clawscli/claws/custom/backup/plans"
	_ "github.com/clawscli/claws/custom/backup/protected-resources"
	_ "github.com/clawscli/claws/custom/backup/recovery-points"
	_ "github.com/clawscli/claws/custom/backup/restore-jobs"
	_ "github.com/clawscli/claws/custom/backup/selections"
	_ "github.com/clawscli/claws/custom/backup/vaults"

	// Batch
	_ "github.com/clawscli/claws/custom/batch/compute-environments"
	_ "github.com/clawscli/claws/custom/batch/job-definitions"
	_ "github.com/clawscli/claws/custom/batch/job-queues"
	_ "github.com/clawscli/claws/custom/batch/jobs"

	// Bedrock
	_ "github.com/clawscli/claws/custom/bedrock/foundation-models"
	_ "github.com/clawscli/claws/custom/bedrock/guardrails"
	_ "github.com/clawscli/claws/custom/bedrock/inference-profiles"

	// Bedrock Agent
	_ "github.com/clawscli/claws/custom/bedrock-agent/agents"
	_ "github.com/clawscli/claws/custom/bedrock-agent/data-sources"
	_ "github.com/clawscli/claws/custom/bedrock-agent/flows"
	_ "github.com/clawscli/claws/custom/bedrock-agent/knowledge-bases"
	_ "github.com/clawscli/claws/custom/bedrock-agent/prompts"

	// Bedrock AgentCore
	_ "github.com/clawscli/claws/custom/bedrock-agentcore/endpoints"
	_ "github.com/clawscli/claws/custom/bedrock-agentcore/runtimes"
	_ "github.com/clawscli/claws/custom/bedrock-agentcore/versions"

	// Budgets
	_ "github.com/clawscli/claws/custom/budgets/budgets"
	_ "github.com/clawscli/claws/custom/budgets/notifications"

	// Cost Explorer
	_ "github.com/clawscli/claws/custom/ce/anomalies"
	_ "github.com/clawscli/claws/custom/ce/costs"
	_ "github.com/clawscli/claws/custom/ce/monitors"

	// CloudFormation
	_ "github.com/clawscli/claws/custom/cloudformation/events"
	_ "github.com/clawscli/claws/custom/cloudformation/outputs"
	_ "github.com/clawscli/claws/custom/cloudformation/resources"
	_ "github.com/clawscli/claws/custom/cloudformation/stacks"

	// CloudFront
	_ "github.com/clawscli/claws/custom/cloudfront/distributions"

	// CloudTrail
	_ "github.com/clawscli/claws/custom/cloudtrail/events"
	_ "github.com/clawscli/claws/custom/cloudtrail/trails"

	// CloudWatch
	_ "github.com/clawscli/claws/custom/cloudwatch/alarms"
	_ "github.com/clawscli/claws/custom/cloudwatch/log-groups"
	_ "github.com/clawscli/claws/custom/cloudwatch/log-streams"

	// CodeBuild
	_ "github.com/clawscli/claws/custom/codebuild/builds"
	_ "github.com/clawscli/claws/custom/codebuild/projects"

	// CodePipeline
	_ "github.com/clawscli/claws/custom/codepipeline/executions"
	_ "github.com/clawscli/claws/custom/codepipeline/pipelines"

	// Cognito
	_ "github.com/clawscli/claws/custom/cognito-idp/user-pools"
	_ "github.com/clawscli/claws/custom/cognito-idp/users"

	// Compute Optimizer
	_ "github.com/clawscli/claws/custom/compute-optimizer/recommendations"
	_ "github.com/clawscli/claws/custom/compute-optimizer/summary"

	// Config
	_ "github.com/clawscli/claws/custom/configservice/rules"

	// DataSync
	_ "github.com/clawscli/claws/custom/datasync/locations"
	_ "github.com/clawscli/claws/custom/datasync/task-executions"
	_ "github.com/clawscli/claws/custom/datasync/tasks"

	// Detective
	_ "github.com/clawscli/claws/custom/detective/graphs"
	_ "github.com/clawscli/claws/custom/detective/investigations"

	// Direct Connect
	_ "github.com/clawscli/claws/custom/directconnect/connections"
	_ "github.com/clawscli/claws/custom/directconnect/virtual-interfaces"

	// DynamoDB
	_ "github.com/clawscli/claws/custom/dynamodb/tables"

	// EC2
	_ "github.com/clawscli/claws/custom/ec2/capacity-reservations"
	_ "github.com/clawscli/claws/custom/ec2/elastic-ips"
	_ "github.com/clawscli/claws/custom/ec2/images"
	_ "github.com/clawscli/claws/custom/ec2/instances"
	_ "github.com/clawscli/claws/custom/ec2/key-pairs"
	_ "github.com/clawscli/claws/custom/ec2/launch-templates"
	_ "github.com/clawscli/claws/custom/ec2/security-groups"
	_ "github.com/clawscli/claws/custom/ec2/snapshots"
	_ "github.com/clawscli/claws/custom/ec2/volumes"

	// ECR
	_ "github.com/clawscli/claws/custom/ecr/images"
	_ "github.com/clawscli/claws/custom/ecr/repositories"

	// ECS
	_ "github.com/clawscli/claws/custom/ecs/clusters"
	_ "github.com/clawscli/claws/custom/ecs/services"
	_ "github.com/clawscli/claws/custom/ecs/task-definitions"
	_ "github.com/clawscli/claws/custom/ecs/tasks"

	// EKS
	_ "github.com/clawscli/claws/custom/eks/access-entries"
	_ "github.com/clawscli/claws/custom/eks/addons"
	_ "github.com/clawscli/claws/custom/eks/clusters"
	_ "github.com/clawscli/claws/custom/eks/fargate-profiles"
	_ "github.com/clawscli/claws/custom/eks/node-groups"

	// ElastiCache
	_ "github.com/clawscli/claws/custom/elasticache/clusters"

	// Elastic Load Balancing
	_ "github.com/clawscli/claws/custom/elbv2/load-balancers"
	_ "github.com/clawscli/claws/custom/elbv2/target-groups"
	_ "github.com/clawscli/claws/custom/elbv2/targets"

	// EMR
	_ "github.com/clawscli/claws/custom/emr/clusters"
	_ "github.com/clawscli/claws/custom/emr/steps"

	// EventBridge
	_ "github.com/clawscli/claws/custom/events/buses"
	_ "github.com/clawscli/claws/custom/events/rules"

	// Firewall Manager
	_ "github.com/clawscli/claws/custom/fms/policies"

	// GameLift
	_ "github.com/clawscli/claws/custom/gamelift/builds"
	_ "github.com/clawscli/claws/custom/gamelift/fleets"
	_ "github.com/clawscli/claws/custom/gamelift/game-session-queues"
	_ "github.com/clawscli/claws/custom/gamelift/game-sessions"
	_ "github.com/clawscli/claws/custom/gamelift/matchmaking-configs"
	_ "github.com/clawscli/claws/custom/gamelift/scripts"

	// Glue
	_ "github.com/clawscli/claws/custom/glue/crawlers"
	_ "github.com/clawscli/claws/custom/glue/databases"
	_ "github.com/clawscli/claws/custom/glue/job-runs"
	_ "github.com/clawscli/claws/custom/glue/jobs"
	_ "github.com/clawscli/claws/custom/glue/tables"

	// GuardDuty
	_ "github.com/clawscli/claws/custom/guardduty/detectors"
	_ "github.com/clawscli/claws/custom/guardduty/findings"

	// Health
	_ "github.com/clawscli/claws/custom/health/events"

	// IAM
	_ "github.com/clawscli/claws/custom/iam/groups"
	_ "github.com/clawscli/claws/custom/iam/instance-profiles"
	_ "github.com/clawscli/claws/custom/iam/policies"
	_ "github.com/clawscli/claws/custom/iam/roles"
	_ "github.com/clawscli/claws/custom/iam/users"

	// Inspector
	_ "github.com/clawscli/claws/custom/inspector2/findings"

	// Kinesis
	_ "github.com/clawscli/claws/custom/kinesis/streams"

	// KMS
	_ "github.com/clawscli/claws/custom/kms/keys"

	// Lambda
	_ "github.com/clawscli/claws/custom/lambda/functions"

	// License Manager
	_ "github.com/clawscli/claws/custom/license-manager/configurations"
	_ "github.com/clawscli/claws/custom/license-manager/grants"
	_ "github.com/clawscli/claws/custom/license-manager/licenses"

	// Macie
	_ "github.com/clawscli/claws/custom/macie2/buckets"
	_ "github.com/clawscli/claws/custom/macie2/classification-jobs"
	_ "github.com/clawscli/claws/custom/macie2/findings"

	// Network Firewall
	_ "github.com/clawscli/claws/custom/network-firewall/firewall-policies"
	_ "github.com/clawscli/claws/custom/network-firewall/firewalls"
	_ "github.com/clawscli/claws/custom/network-firewall/rule-groups"

	// OpenSearch
	_ "github.com/clawscli/claws/custom/opensearch/domains"

	// Organizations
	_ "github.com/clawscli/claws/custom/organizations/accounts"
	_ "github.com/clawscli/claws/custom/organizations/ous"
	_ "github.com/clawscli/claws/custom/organizations/policies"
	_ "github.com/clawscli/claws/custom/organizations/roots"

	// RDS
	_ "github.com/clawscli/claws/custom/rds/instances"
	_ "github.com/clawscli/claws/custom/rds/snapshots"

	// Redshift
	_ "github.com/clawscli/claws/custom/redshift/clusters"
	_ "github.com/clawscli/claws/custom/redshift/snapshots"

	// RI/SP
	_ "github.com/clawscli/claws/custom/risp/reserved-instances"
	_ "github.com/clawscli/claws/custom/risp/savings-plans"

	// Route 53
	_ "github.com/clawscli/claws/custom/route53/hosted-zones"
	_ "github.com/clawscli/claws/custom/route53/record-sets"

	// S3
	_ "github.com/clawscli/claws/custom/s3/buckets"

	// S3 Vectors
	_ "github.com/clawscli/claws/custom/s3vectors/buckets"
	_ "github.com/clawscli/claws/custom/s3vectors/indexes"

	// SageMaker
	_ "github.com/clawscli/claws/custom/sagemaker/endpoints"
	_ "github.com/clawscli/claws/custom/sagemaker/models"
	_ "github.com/clawscli/claws/custom/sagemaker/notebooks"
	_ "github.com/clawscli/claws/custom/sagemaker/training-jobs"

	// Secrets Manager
	_ "github.com/clawscli/claws/custom/secretsmanager/secrets"

	// Security Hub
	_ "github.com/clawscli/claws/custom/securityhub/findings"

	// Service Quotas
	_ "github.com/clawscli/claws/custom/service-quotas/quotas"
	_ "github.com/clawscli/claws/custom/service-quotas/services"

	// SNS
	_ "github.com/clawscli/claws/custom/sns/subscriptions"
	_ "github.com/clawscli/claws/custom/sns/topics"

	// SQS
	_ "github.com/clawscli/claws/custom/sqs/queues"

	// Systems Manager
	_ "github.com/clawscli/claws/custom/ssm/parameters"

	// Step Functions
	_ "github.com/clawscli/claws/custom/stepfunctions/executions"
	_ "github.com/clawscli/claws/custom/stepfunctions/state-machines"

	// Transcribe
	_ "github.com/clawscli/claws/custom/transcribe/jobs"

	// Transfer Family
	_ "github.com/clawscli/claws/custom/transfer/servers"
	_ "github.com/clawscli/claws/custom/transfer/users"

	// Trusted Advisor
	_ "github.com/clawscli/claws/custom/trustedadvisor/recommendations"

	// VPC
	_ "github.com/clawscli/claws/custom/vpc/endpoints"
	_ "github.com/clawscli/claws/custom/vpc/internet-gateways"
	_ "github.com/clawscli/claws/custom/vpc/nat-gateways"
	_ "github.com/clawscli/claws/custom/vpc/route-tables"
	_ "github.com/clawscli/claws/custom/vpc/subnets"
	_ "github.com/clawscli/claws/custom/vpc/tgw-attachments"
	_ "github.com/clawscli/claws/custom/vpc/transit-gateways"
	_ "github.com/clawscli/claws/custom/vpc/vpcs"

	// WAF
	_ "github.com/clawscli/claws/custom/wafv2/web-acls"

	// X-Ray
	_ "github.com/clawscli/claws/custom/xray/groups"
)
