// Code generated by go generate; DO NOT EDIT.
// To regenerate: task gen-imports

package jobqueues

// ServiceResourcePath is the canonical path for this resource type.
const ServiceResourcePath = "batch/job-queues"
