// Code generated by go generate; DO NOT EDIT.
// To regenerate: task gen-imports

package matchmakingconfigs

// ServiceResourcePath is the canonical path for this resource type.
const ServiceResourcePath = "gamelift/matchmaking-configs"
