// Code generated by go generate; DO NOT EDIT.
// To regenerate: task gen-imports

package servers

// ServiceResourcePath is the canonical path for this resource type.
const ServiceResourcePath = "transfer/servers"
