// Code generated by go generate; DO NOT EDIT.
// To regenerate: task gen-imports

package rulegroups

// ServiceResourcePath is the canonical path for this resource type.
const ServiceResourcePath = "network-firewall/rule-groups"
