// Code generated by go generate; DO NOT EDIT.
// To regenerate: task gen-imports

package savingsplans

// ServiceResourcePath is the canonical path for this resource type.
const ServiceResourcePath = "risp/savings-plans"
