// Code generated by go generate; DO NOT EDIT.
// To regenerate: task gen-imports

package stagesv2

// ServiceResourcePath is the canonical path for this resource type.
const ServiceResourcePath = "apigateway/stages-v2"
