// Code generated by go generate; DO NOT EDIT.
// To regenerate: task gen-imports

package webacls

// ServiceResourcePath is the canonical path for this resource type.
const ServiceResourcePath = "wafv2/web-acls"
