// Code generated by go generate; DO NOT EDIT.
// To regenerate: task gen-imports

package findings

// ServiceResourcePath is the canonical path for this resource type.
const ServiceResourcePath = "macie2/findings"
